name: develop

on:
  - push
  - pull_request

jobs:

  develop:
    name: develop
    runs-on: ubuntu-22.04
    steps:

      - name: setup-wasi-sdk
        run: |
          df -hT
          exit 1

      - name: codegen
        run: |
          cabal v2-run libffi-wasm32
