name: shell

on:
  - push
  - pull_request

jobs:

  shell:
    name: shell
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup-nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: setup-cachix
        uses: cachix/cachix-action@v10
        with:
          name: asterius
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: cachix-watch-store
        if: ${{ github.repository_owner == 'tweag' }}
        run: |
          cachix watch-store -c9 -j2 asterius &

      - name: build
        run: |
          cp $(nix build --json --no-link -f nix/top.nix cbits | jq -r '.[0].outputs.cbits')/* cbits

      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: cbits
          path: cbits
